/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NewRouteImport } from './routes/new'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatSessionKeyRouteImport } from './routes/chat/$sessionKey'
import { Route as ApiWorkingMemoryRouteImport } from './routes/api/working-memory'
import { Route as ApiVaultRouteImport } from './routes/api/vault'
import { Route as ApiUsageRouteImport } from './routes/api/usage'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiStreamRouteImport } from './routes/api/stream'
import { Route as ApiSessionsRouteImport } from './routes/api/sessions'
import { Route as ApiSendRouteImport } from './routes/api/send'
import { Route as ApiProviderKeyRouteImport } from './routes/api/provider-key'
import { Route as ApiProjectsRouteImport } from './routes/api/projects'
import { Route as ApiPingRouteImport } from './routes/api/ping'
import { Route as ApiPathsRouteImport } from './routes/api/paths'
import { Route as ApiPairingRouteImport } from './routes/api/pairing'
import { Route as ApiOnboardingRouteImport } from './routes/api/onboarding'
import { Route as ApiHistoryRouteImport } from './routes/api/history'
import { Route as ApiArtifactRouteImport } from './routes/api/artifact'
import { Route as ApiProviderKeyTestRouteImport } from './routes/api/provider-key/test'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatSessionKeyRoute = ChatSessionKeyRouteImport.update({
  id: '/chat/$sessionKey',
  path: '/chat/$sessionKey',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkingMemoryRoute = ApiWorkingMemoryRouteImport.update({
  id: '/api/working-memory',
  path: '/api/working-memory',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVaultRoute = ApiVaultRouteImport.update({
  id: '/api/vault',
  path: '/api/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsageRoute = ApiUsageRouteImport.update({
  id: '/api/usage',
  path: '/api/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamRoute = ApiStreamRouteImport.update({
  id: '/api/stream',
  path: '/api/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsRoute = ApiSessionsRouteImport.update({
  id: '/api/sessions',
  path: '/api/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendRoute = ApiSendRouteImport.update({
  id: '/api/send',
  path: '/api/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProviderKeyRoute = ApiProviderKeyRouteImport.update({
  id: '/api/provider-key',
  path: '/api/provider-key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPingRoute = ApiPingRouteImport.update({
  id: '/api/ping',
  path: '/api/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPathsRoute = ApiPathsRouteImport.update({
  id: '/api/paths',
  path: '/api/paths',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPairingRoute = ApiPairingRouteImport.update({
  id: '/api/pairing',
  path: '/api/pairing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOnboardingRoute = ApiOnboardingRouteImport.update({
  id: '/api/onboarding',
  path: '/api/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryRoute = ApiHistoryRouteImport.update({
  id: '/api/history',
  path: '/api/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArtifactRoute = ApiArtifactRouteImport.update({
  id: '/api/artifact',
  path: '/api/artifact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProviderKeyTestRoute = ApiProviderKeyTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => ApiProviderKeyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/new': typeof NewRoute
  '/onboarding': typeof OnboardingRoute
  '/api/artifact': typeof ApiArtifactRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/onboarding': typeof ApiOnboardingRoute
  '/api/pairing': typeof ApiPairingRoute
  '/api/paths': typeof ApiPathsRoute
  '/api/ping': typeof ApiPingRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/provider-key': typeof ApiProviderKeyRouteWithChildren
  '/api/send': typeof ApiSendRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/usage': typeof ApiUsageRoute
  '/api/vault': typeof ApiVaultRoute
  '/api/working-memory': typeof ApiWorkingMemoryRoute
  '/chat/$sessionKey': typeof ChatSessionKeyRoute
  '/api/provider-key/test': typeof ApiProviderKeyTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/new': typeof NewRoute
  '/onboarding': typeof OnboardingRoute
  '/api/artifact': typeof ApiArtifactRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/onboarding': typeof ApiOnboardingRoute
  '/api/pairing': typeof ApiPairingRoute
  '/api/paths': typeof ApiPathsRoute
  '/api/ping': typeof ApiPingRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/provider-key': typeof ApiProviderKeyRouteWithChildren
  '/api/send': typeof ApiSendRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/usage': typeof ApiUsageRoute
  '/api/vault': typeof ApiVaultRoute
  '/api/working-memory': typeof ApiWorkingMemoryRoute
  '/chat/$sessionKey': typeof ChatSessionKeyRoute
  '/api/provider-key/test': typeof ApiProviderKeyTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/new': typeof NewRoute
  '/onboarding': typeof OnboardingRoute
  '/api/artifact': typeof ApiArtifactRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/onboarding': typeof ApiOnboardingRoute
  '/api/pairing': typeof ApiPairingRoute
  '/api/paths': typeof ApiPathsRoute
  '/api/ping': typeof ApiPingRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/provider-key': typeof ApiProviderKeyRouteWithChildren
  '/api/send': typeof ApiSendRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/usage': typeof ApiUsageRoute
  '/api/vault': typeof ApiVaultRoute
  '/api/working-memory': typeof ApiWorkingMemoryRoute
  '/chat/$sessionKey': typeof ChatSessionKeyRoute
  '/api/provider-key/test': typeof ApiProviderKeyTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect'
    | '/new'
    | '/onboarding'
    | '/api/artifact'
    | '/api/history'
    | '/api/onboarding'
    | '/api/pairing'
    | '/api/paths'
    | '/api/ping'
    | '/api/projects'
    | '/api/provider-key'
    | '/api/send'
    | '/api/sessions'
    | '/api/stream'
    | '/api/transcribe'
    | '/api/usage'
    | '/api/vault'
    | '/api/working-memory'
    | '/chat/$sessionKey'
    | '/api/provider-key/test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connect'
    | '/new'
    | '/onboarding'
    | '/api/artifact'
    | '/api/history'
    | '/api/onboarding'
    | '/api/pairing'
    | '/api/paths'
    | '/api/ping'
    | '/api/projects'
    | '/api/provider-key'
    | '/api/send'
    | '/api/sessions'
    | '/api/stream'
    | '/api/transcribe'
    | '/api/usage'
    | '/api/vault'
    | '/api/working-memory'
    | '/chat/$sessionKey'
    | '/api/provider-key/test'
  id:
    | '__root__'
    | '/'
    | '/connect'
    | '/new'
    | '/onboarding'
    | '/api/artifact'
    | '/api/history'
    | '/api/onboarding'
    | '/api/pairing'
    | '/api/paths'
    | '/api/ping'
    | '/api/projects'
    | '/api/provider-key'
    | '/api/send'
    | '/api/sessions'
    | '/api/stream'
    | '/api/transcribe'
    | '/api/usage'
    | '/api/vault'
    | '/api/working-memory'
    | '/chat/$sessionKey'
    | '/api/provider-key/test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectRoute: typeof ConnectRoute
  NewRoute: typeof NewRoute
  OnboardingRoute: typeof OnboardingRoute
  ApiArtifactRoute: typeof ApiArtifactRoute
  ApiHistoryRoute: typeof ApiHistoryRoute
  ApiOnboardingRoute: typeof ApiOnboardingRoute
  ApiPairingRoute: typeof ApiPairingRoute
  ApiPathsRoute: typeof ApiPathsRoute
  ApiPingRoute: typeof ApiPingRoute
  ApiProjectsRoute: typeof ApiProjectsRoute
  ApiProviderKeyRoute: typeof ApiProviderKeyRouteWithChildren
  ApiSendRoute: typeof ApiSendRoute
  ApiSessionsRoute: typeof ApiSessionsRoute
  ApiStreamRoute: typeof ApiStreamRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ApiUsageRoute: typeof ApiUsageRoute
  ApiVaultRoute: typeof ApiVaultRoute
  ApiWorkingMemoryRoute: typeof ApiWorkingMemoryRoute
  ChatSessionKeyRoute: typeof ChatSessionKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$sessionKey': {
      id: '/chat/$sessionKey'
      path: '/chat/$sessionKey'
      fullPath: '/chat/$sessionKey'
      preLoaderRoute: typeof ChatSessionKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/working-memory': {
      id: '/api/working-memory'
      path: '/api/working-memory'
      fullPath: '/api/working-memory'
      preLoaderRoute: typeof ApiWorkingMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vault': {
      id: '/api/vault'
      path: '/api/vault'
      fullPath: '/api/vault'
      preLoaderRoute: typeof ApiVaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/usage': {
      id: '/api/usage'
      path: '/api/usage'
      fullPath: '/api/usage'
      preLoaderRoute: typeof ApiUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream': {
      id: '/api/stream'
      path: '/api/stream'
      fullPath: '/api/stream'
      preLoaderRoute: typeof ApiStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions': {
      id: '/api/sessions'
      path: '/api/sessions'
      fullPath: '/api/sessions'
      preLoaderRoute: typeof ApiSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send': {
      id: '/api/send'
      path: '/api/send'
      fullPath: '/api/send'
      preLoaderRoute: typeof ApiSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/provider-key': {
      id: '/api/provider-key'
      path: '/api/provider-key'
      fullPath: '/api/provider-key'
      preLoaderRoute: typeof ApiProviderKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ping': {
      id: '/api/ping'
      path: '/api/ping'
      fullPath: '/api/ping'
      preLoaderRoute: typeof ApiPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paths': {
      id: '/api/paths'
      path: '/api/paths'
      fullPath: '/api/paths'
      preLoaderRoute: typeof ApiPathsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pairing': {
      id: '/api/pairing'
      path: '/api/pairing'
      fullPath: '/api/pairing'
      preLoaderRoute: typeof ApiPairingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/onboarding': {
      id: '/api/onboarding'
      path: '/api/onboarding'
      fullPath: '/api/onboarding'
      preLoaderRoute: typeof ApiOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history': {
      id: '/api/history'
      path: '/api/history'
      fullPath: '/api/history'
      preLoaderRoute: typeof ApiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/artifact': {
      id: '/api/artifact'
      path: '/api/artifact'
      fullPath: '/api/artifact'
      preLoaderRoute: typeof ApiArtifactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/provider-key/test': {
      id: '/api/provider-key/test'
      path: '/test'
      fullPath: '/api/provider-key/test'
      preLoaderRoute: typeof ApiProviderKeyTestRouteImport
      parentRoute: typeof ApiProviderKeyRoute
    }
  }
}

interface ApiProviderKeyRouteChildren {
  ApiProviderKeyTestRoute: typeof ApiProviderKeyTestRoute
}

const ApiProviderKeyRouteChildren: ApiProviderKeyRouteChildren = {
  ApiProviderKeyTestRoute: ApiProviderKeyTestRoute,
}

const ApiProviderKeyRouteWithChildren = ApiProviderKeyRoute._addFileChildren(
  ApiProviderKeyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectRoute: ConnectRoute,
  NewRoute: NewRoute,
  OnboardingRoute: OnboardingRoute,
  ApiArtifactRoute: ApiArtifactRoute,
  ApiHistoryRoute: ApiHistoryRoute,
  ApiOnboardingRoute: ApiOnboardingRoute,
  ApiPairingRoute: ApiPairingRoute,
  ApiPathsRoute: ApiPathsRoute,
  ApiPingRoute: ApiPingRoute,
  ApiProjectsRoute: ApiProjectsRoute,
  ApiProviderKeyRoute: ApiProviderKeyRouteWithChildren,
  ApiSendRoute: ApiSendRoute,
  ApiSessionsRoute: ApiSessionsRoute,
  ApiStreamRoute: ApiStreamRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ApiUsageRoute: ApiUsageRoute,
  ApiVaultRoute: ApiVaultRoute,
  ApiWorkingMemoryRoute: ApiWorkingMemoryRoute,
  ChatSessionKeyRoute: ChatSessionKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
